// 공고 데이터 - 기본 공고는 이 파일에서 관리합니다.
//
// source:
// - "seoulbar"  : 서울지방변호사회 공고. 공고 상세 필드를 직접 입력합니다.
// - "jobcenter" : 취업정보센터 공고. 외부 게시글 링크만 입력합니다.
//
// stage:
// - "hidden"    : 채용단계 표시 안 함
// - "interview" : 면접 진행 중
// - "done"      : 채용 완료

const POSTINGS = [
  {
    id: 1,
    source: "seoulbar",
    firm: "법률사무소 동락",
    title: "신입변호사 모집",
    deadline: "2026-05-06",
    postedAt: "2026-04-06",
    stage: "interview",
    stageCheckedAt: "2026-05-09",
    location: "서울 성동구 아차산로17길 48 성수 SK V1 CENTER I 306호",
    salary: "월 300~350만원 (세전)",
    workHours: "09:00~18:00 (월~금)",
    contact: "02-446-8490",
    representative: "이무섭, 정영선 변호사",
    size: "변호사 3명, 사무원 1명",
    jobType: "실무수습 변호사 (지식재산 분쟁 등)\n채용형태: 정규직, 채용인원: 1명",
    startDate: "2026-05-26",
    requirements: "제15회 변호사시험 합격자",
    process: "1차 서류(~05-06) -> 2차 면접(~05-20)",
    documents: "이력서 및 자기소개서",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자유롭게 기술",
    applicationEmail: "yschung@donglaklaw.com",
    notifyMethod: "전화 또는 이메일 연락",
    homepage: "https://www.donglaklaw.com",
    benefits: "4대보험, 식비, 연차, 출산/생리휴가, 육아휴직",
    description: ""
  },
  {
    id: 2,
    source: "seoulbar",
    firm: "법무법인 창세",
    title: "신입변호사 채용",
    deadline: "2026-05-14",
    postedAt: "2026-05-09",
    stage: "interview",
    stageCheckedAt: "2026-05-09 16:00",
    location: "서울 서초구 서초대로 254 오퓨런스 7층 710호",
    salary: "월 600만원 이상 (세전)",
    workHours: "09:30~18:30 (월~금), 휴게시간 11:30~12:30",
    contact: "02-6013-6117 / 010-3596-1544",
    representative: "김정묵, 박영재",
    size: "변호사 3명, 직원 3명",
    jobType: "정규직, 1명",
    startDate: "2026-05-25",
    requirements: "무관",
    process: "1차 서류(~05-18) -> 2차 면접(~05-25)",
    documents: "이력서",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자기소개서 별도 제출 없음",
    applicationEmail: "mkshin@changselaw.com",
    notifyMethod: "1차 서류 심사 후 유선 개별통보",
    homepage: "https://www.changselaw.com",
    benefits: "4대보험, 식비, 연차, 개인사무공간 제공, 출장용 법인카드 지원",
    description: "민사, 형사, 행정 사건 소송 수행, 준비서면 작성, 법원·경찰·노동청 출석, 의뢰인 상담 및 사건 관리."
  },
  {
    id: 3,
    source: "seoulbar",
    firm: "법무법인 예시",
    title: "신입변호사 채용",
    deadline: "2026-05-20",
    postedAt: "2026-05-10",
    stage: "interview",
    stageCheckedAt: "2026-05-10",
    location: "서울 서초구 ...",
    salary: "월 500만원 이상",
    workHours: "09:00~18:00",
    applicationEmail: "recruit@example.com",
    contact: "",
    representative: "",
    size: "",
    jobType: "",
    startDate: "",
    requirements: "",
    process: "",
    documents: "",
    resumeItems: "",
    coverLetterItems: "",
    notifyMethod: "",
    homepage: "",
    benefits: "",
    description: ""
  },
  {
    id: 4,
    source: "jobcenter",
    firm: "취업정보센터",
    title: "취업정보센터 공고 예시",
    postedAt: "2026-05-10",
    deadline: "2026-05-31",
    stage: "interview",
    stageCheckedAt: "",
    externalUrl: "https://www.koreanbar.or.kr"
  },
  {
    id: 5,
    source: "seoulbar",
    firm: "법무법인 강헌",
    title: "수습변호사 채용합니다.",
    postedAt: "2026-05-11",
    deadline: "2026-05-11",
    stage: "hidden",
    stageCheckedAt: "",
    address: "06142\n서울 강남구 테헤란로37길 7 (역삼동, 조이타워)\n4층 법무법인 강헌",
    representative: "이찬승",
    homepage: "https://kangheon.co.kr/",
    contact: "01062031483",
    sizeAndEtc: "변호사 6명, 직원 5명",
    hiringCount: "채용분야 : 기업자문, 일반 민/형사, 가사\n변 호 사 : 1명",
    employmentType: "기타 ( 수습변호사 )",
    duties: "기업자문(인수/합병 등 포함), 형사/민사 서면작성, 판례조사 등",
    workStartDate: "2026-05-19",
    dailyWorkHours: "출근시간 : 9시 20분\n퇴근시간 : 6시 20분\n휴게시간 : 12시 0분 ~ 13시 0분\n기타 :",
    wage: "월 300만원 ~ 350만원 (세전)",
    overtimePay: "근로기준법에 따름",
    workPlace: "사무실",
    workDays: "월~금(주5일)",
    holidays: "토,일,법정공휴일",
    annualLeave: "있음",
    fourInsurances: "있음",
    maternityLeave: "있음",
    menstrualLeave: "있음",
    parentalLeave: "기타 ( 수습기간이후있음 )",
    bonus: "기타 ( 실적고려 지급 )",
    mealSupport: "있음",
    otherBenefits: "명절비 지급",
    career: "기타 ( 수습변호사 )",
    certifications: "",
    otherRequirements: "",
    preferences: "MS오피스 사용가능자",
    documents: "기타 ( 이력서, 자기소개서, 로스쿨 성적증명원 )",
    process: "1차 서류전형 ( 일정 : 2026-05-14 )\n2차 면접 ( 일정 : 2026-05-18 )\n기타 :",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자유롭게 기술",
    applicationDeadline: "2026-05-11",
    notifyMethod: "문자로 안내드립니다.",
    applicationMethod: "이메일 : lawyers78@naver.com\n팩   스 : 02-3474-2201\n기   타 :",
    manager: "이   름 : 김지호 변호사\n연락처 : 01062031483",
    description: "법무법인 강헌과 함께하실 변호사님을 모십니다. 법무법인 강헌에서는 기업법무, 일반 형사/민사, 가사, 행정사건 등을 폭넓게 다루고 있어서, 입사시 다양한 사건을 경험해보실수 있습니다.\n수습기간 종료 이후, 정식채용을 고려하고 있습니다.\n많은 지원 바랍니다."
  },
  {
    id: 6,
    source: "seoulbar",
    firm: "법무법인(유한)금성",
    title: "수습변호사 채용",
    postedAt: "2026-05-11",
    deadline: "2026-06-11",
    stage: "hidden",
    stageCheckedAt: "",
    address: "06647\n서울 서초구 반포대로30길 12-6 (서초동, 지방공기업평가원)\n4층",
    representative: "하윤홍 변호",
    homepage: "https://www.keumseong.com/",
    contact: "02-3437-5130",
    sizeAndEtc: "변호사 20명",
    hiringCount: "채용분야 :\n변 호 사 : 1명",
    employmentType: "기타 ( 실무수습 후 정규직 전환 예정 )",
    duties: "변호사업무(기록 검토, 서면 작성, 기업 법률자문, 재판참관 등)",
    workStartDate: "2026-05-26",
    dailyWorkHours: "출근시간 : 9시 0분\n퇴근시간 : 18시 0분\n휴게시간 : 12시 0분 ~ 13시 0분\n기타 :",
    wage: "월 250만원 ~ 300만원 (세전)",
    overtimePay: "근로기준법에 따름",
    workPlace: "사무실",
    workDays: "월~금(주5일)",
    holidays: "토,일,법정공휴일",
    annualLeave: "있음",
    fourInsurances: "있음",
    maternityLeave: "있음",
    menstrualLeave: "있음",
    parentalLeave: "있음",
    bonus: "없음",
    mealSupport: "있음",
    otherBenefits: "통신비지원",
    career: "기타 ( 제15회 변호사시험 합격자 )",
    certifications: "",
    otherRequirements: "",
    preferences: "",
    documents: "기타 ( ① 이력서, ② 자기소개서, ③ 변호사시험 성적표, ④ 로스쿨 성적증명서 )",
    process: "1차 서류전형 ( 일정 : 2026-05-15 )\n2차 면접 ( 일정 : 2026-05-20 )\n기타 :",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자유롭게 기술",
    applicationDeadline: "2026-06-11",
    notifyMethod: "개별통보",
    applicationMethod: "이메일 : jaebeum800@gmail.com\n팩   스 : 02-3437-5130\n기   타 :",
    manager: "이   름 : 조현정 과장\n연락처 : 02-3437-5130",
    description: "법무법인(유한) 금성은 화재, 건축, 재개발, 외국인 및 출입국, 기업회생 사건 등 각 분야에 특화된 전문성을 보유한 로펌입니다.\n\n법무법인(유한)금성 변호사 박재범 건축팀(건축, 조합 자문 및 소송 위주)에서 수습변호사님을 채용하고자 합니다.\n\n수습기간 종료 후 협의하여 정규직 채용을 전제로 근무하실 분을 모집하오니 제15회 변호사시험 합격자분들의 많은 관심과 지원을 기다리겠습니다"
  }
];
