// 공고 데이터 - 기본 공고는 이 파일에서 관리합니다.
//
// source:
// - "seoulbar"  : 서울지방변호사회 공고. 공고 상세 필드를 직접 입력합니다.
// - "jobcenter" : 취업정보센터 공고. 외부 게시글 링크만 입력합니다.
//
// stage:
// - "hidden"    : 채용단계 표시 안 함
// - "interview" : 면접 진행 중
// - "done"      : 채용 완료

const POSTINGS = [
  {
    id: 1,
    source: "seoulbar",
    firm: "법률사무소 동락",
    title: "신입변호사 모집",
    deadline: "2026-05-06",
    postedAt: "2026-04-06",
    stage: "interview",
    stageCheckedAt: "2026-05-09",
    location: "서울 성동구 아차산로17길 48 성수 SK V1 CENTER I 306호",
    salary: "월 300~350만원 (세전)",
    workHours: "09:00~18:00 (월~금)",
    contact: "02-446-8490",
    representative: "이무섭, 정영선 변호사",
    size: "변호사 3명, 사무원 1명",
    jobType: "실무수습 변호사 (지식재산 분쟁 등)\n채용형태: 정규직, 채용인원: 1명",
    startDate: "2026-05-26",
    requirements: "제15회 변호사시험 합격자",
    process: "1차 서류(~05-06) -> 2차 면접(~05-20)",
    documents: "이력서 및 자기소개서",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자유롭게 기술",
    applicationEmail: "yschung@donglaklaw.com",
    notifyMethod: "전화 또는 이메일 연락",
    homepage: "https://www.donglaklaw.com",
    benefits: "4대보험, 식비, 연차, 출산/생리휴가, 육아휴직",
    description: ""
  },
  {
    id: 2,
    source: "seoulbar",
    firm: "법무법인 창세",
    title: "신입변호사 채용",
    deadline: "2026-05-14",
    postedAt: "2026-05-09",
    stage: "interview",
    stageCheckedAt: "2026-05-09 16:00",
    location: "서울 서초구 서초대로 254 오퓨런스 7층 710호",
    salary: "월 600만원 이상 (세전)",
    workHours: "09:30~18:30 (월~금), 휴게시간 11:30~12:30",
    contact: "02-6013-6117 / 010-3596-1544",
    representative: "김정묵, 박영재",
    size: "변호사 3명, 직원 3명",
    jobType: "정규직, 1명",
    startDate: "2026-05-25",
    requirements: "무관",
    process: "1차 서류(~05-18) -> 2차 면접(~05-25)",
    documents: "이력서",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자기소개서 별도 제출 없음",
    applicationEmail: "mkshin@changselaw.com",
    notifyMethod: "1차 서류 심사 후 유선 개별통보",
    homepage: "https://www.changselaw.com",
    benefits: "4대보험, 식비, 연차, 개인사무공간 제공, 출장용 법인카드 지원",
    description: "민사, 형사, 행정 사건 소송 수행, 준비서면 작성, 법원·경찰·노동청 출석, 의뢰인 상담 및 사건 관리."
  },
  {
    id: 3,
    source: "seoulbar",
    firm: "법무법인 예시",
    title: "신입변호사 채용",
    deadline: "2026-05-20",
    postedAt: "2026-05-10",
    stage: "interview",
    stageCheckedAt: "2026-05-10",
    location: "서울 서초구 ...",
    salary: "월 500만원 이상",
    workHours: "09:00~18:00",
    applicationEmail: "recruit@example.com",
    contact: "",
    representative: "",
    size: "",
    jobType: "",
    startDate: "",
    requirements: "",
    process: "",
    documents: "",
    resumeItems: "",
    coverLetterItems: "",
    notifyMethod: "",
    homepage: "",
    benefits: "",
    description: ""
  },
  {
    id: 4,
    source: "jobcenter",
    firm: "취업정보센터",
    title: "취업정보센터 공고 예시",
    postedAt: "2026-05-10",
    deadline: "2026-05-31",
    stage: "interview",
    stageCheckedAt: "",
    externalUrl: "https://www.koreanbar.or.kr"
  },
  {
    id: 5,
    source: "seoulbar",
    firm: "법무법인 강헌",
    title: "수습변호사 채용합니다.",
    postedAt: "2026-05-11",
    deadline: "2026-05-11",
    stage: "hidden",
    stageCheckedAt: "",
    address: "06142\n서울 강남구 테헤란로37길 7 (역삼동, 조이타워)\n4층 법무법인 강헌",
    representative: "이찬승",
    homepage: "https://kangheon.co.kr/",
    contact: "01062031483",
    sizeAndEtc: "변호사 6명, 직원 5명",
    hiringCount: "채용분야 : 기업자문, 일반 민/형사, 가사\n변 호 사 : 1명",
    employmentType: "기타 ( 수습변호사 )",
    duties: "기업자문(인수/합병 등 포함), 형사/민사 서면작성, 판례조사 등",
    workStartDate: "2026-05-19",
    dailyWorkHours: "출근시간 : 9시 20분\n퇴근시간 : 6시 20분\n휴게시간 : 12시 0분 ~ 13시 0분\n기타 :",
    wage: "월 300만원 ~ 350만원 (세전)",
    overtimePay: "근로기준법에 따름",
    workPlace: "사무실",
    workDays: "월~금(주5일)",
    holidays: "토,일,법정공휴일",
    annualLeave: "있음",
    fourInsurances: "있음",
    maternityLeave: "있음",
    menstrualLeave: "있음",
    parentalLeave: "기타 ( 수습기간이후있음 )",
    bonus: "기타 ( 실적고려 지급 )",
    mealSupport: "있음",
    otherBenefits: "명절비 지급",
    career: "기타 ( 수습변호사 )",
    certifications: "",
    otherRequirements: "",
    preferences: "MS오피스 사용가능자",
    documents: "기타 ( 이력서, 자기소개서, 로스쿨 성적증명원 )",
    process: "1차 서류전형 ( 일정 : 2026-05-14 )\n2차 면접 ( 일정 : 2026-05-18 )\n기타 :",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자유롭게 기술",
    applicationDeadline: "2026-05-11",
    notifyMethod: "문자로 안내드립니다.",
    applicationMethod: "이메일 : lawyers78@naver.com\n팩   스 : 02-3474-2201\n기   타 :",
    manager: "이   름 : 김지호 변호사\n연락처 : 01062031483",
    description: "법무법인 강헌과 함께하실 변호사님을 모십니다. 법무법인 강헌에서는 기업법무, 일반 형사/민사, 가사, 행정사건 등을 폭넓게 다루고 있어서, 입사시 다양한 사건을 경험해보실수 있습니다.\n수습기간 종료 이후, 정식채용을 고려하고 있습니다.\n많은 지원 바랍니다."
  },
  {
    id: 6,
    source: "seoulbar",
    firm: "법무법인(유한)금성",
    title: "수습변호사 채용",
    postedAt: "2026-05-11",
    deadline: "2026-06-11",
    stage: "hidden",
    stageCheckedAt: "",
    address: "06647\n서울 서초구 반포대로30길 12-6 (서초동, 지방공기업평가원)\n4층",
    representative: "하윤홍 변호",
    homepage: "https://www.keumseong.com/",
    contact: "02-3437-5130",
    sizeAndEtc: "변호사 20명",
    hiringCount: "채용분야 :\n변 호 사 : 1명",
    employmentType: "기타 ( 실무수습 후 정규직 전환 예정 )",
    duties: "변호사업무(기록 검토, 서면 작성, 기업 법률자문, 재판참관 등)",
    workStartDate: "2026-05-26",
    dailyWorkHours: "출근시간 : 9시 0분\n퇴근시간 : 18시 0분\n휴게시간 : 12시 0분 ~ 13시 0분\n기타 :",
    wage: "월 250만원 ~ 300만원 (세전)",
    overtimePay: "근로기준법에 따름",
    workPlace: "사무실",
    workDays: "월~금(주5일)",
    holidays: "토,일,법정공휴일",
    annualLeave: "있음",
    fourInsurances: "있음",
    maternityLeave: "있음",
    menstrualLeave: "있음",
    parentalLeave: "있음",
    bonus: "없음",
    mealSupport: "있음",
    otherBenefits: "통신비지원",
    career: "기타 ( 제15회 변호사시험 합격자 )",
    certifications: "",
    otherRequirements: "",
    preferences: "",
    documents: "기타 ( ① 이력서, ② 자기소개서, ③ 변호사시험 성적표, ④ 로스쿨 성적증명서 )",
    process: "1차 서류전형 ( 일정 : 2026-05-15 )\n2차 면접 ( 일정 : 2026-05-20 )\n기타 :",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자유롭게 기술",
    applicationDeadline: "2026-06-11",
    notifyMethod: "개별통보",
    applicationMethod: "이메일 : jaebeum800@gmail.com\n팩   스 : 02-3437-5130\n기   타 :",
    manager: "이   름 : 조현정 과장\n연락처 : 02-3437-5130",
    description: "법무법인(유한) 금성은 화재, 건축, 재개발, 외국인 및 출입국, 기업회생 사건 등 각 분야에 특화된 전문성을 보유한 로펌입니다.\n\n법무법인(유한)금성 변호사 박재범 건축팀(건축, 조합 자문 및 소송 위주)에서 수습변호사님을 채용하고자 합니다.\n\n수습기간 종료 후 협의하여 정규직 채용을 전제로 근무하실 분을 모집하오니 제15회 변호사시험 합격자분들의 많은 관심과 지원을 기다리겠습니다"
  },
  {
    id: 7,
    source: "seoulbar",
    firm: "법무법인 리율",
    title: "법무법인 리율 신입변호사 채용공고",
    postedAt: "2026-05-11",
    deadline: "2026-05-26",
    stage: "hidden",
    stageCheckedAt: "",
    address: "06744\n서울 서초구 바우뫼로37길 45 (양재동, 영산양재홀)\n2층",
    representative: "김시연, 강지현, 전경준",
    homepage: "https://www.lylaw.kr/",
    contact: "02-573-2632",
    sizeAndEtc: "법무법인 리율은 2026년 2월 10일 설립된 신규 법무법인입니다. 대형법무법인, 대기업 등에서 지식재산권, IT 기술, 금융 서비스 등을 다양하게 경험하고 자신의 업무 분야를 확장해 온 변호사들이 더 전문적인 법률 서비스를 제공하기 위해 법무법인 리율을 설립하였습니다. 이번 채용은 단순한 인력 충원이 아니라, 법무법인의 초기 멤버로서 조직의 성장 과정에 직접 참여하며 장기적인 커리어를 함께 설계해 나갈 변호사님을 모시는 채용입니다. 리율의 김시연 변호사, 강지현 변호사는 설립 초기부터 기술유출, 부정경쟁행위, 영업비밀, 특허·저작권 등 지식재산권 분쟁 및 기업자문 분야에서 강점을 구축해 왔으며, IT(인공지능, 블록체인, S/W 등)·바이오·콘텐츠·제조업 등 첨단 산업과 기업법무 전반에 대한 높은 이해를 바탕으로 실제 기업 현장에서 요구되는 법률문제 해결 역량을 지속적으로 향상시켜 왔습니다. 또한 이번 법무법인 창립 구성원으로서, 20년 이상 M&A 및 금융 분야에서 전문성을 축적하신 전경준 변호사님과 20년 이상 부동산, 건설 분야에서 독보적인 성과를 보여 오신 김종문 변호사님이 대표변호사로 취임하심에 따라, 기존 지식재산권 중심의 실무에 더해 기업자문·금융·부동산·투자 관련 업무로의 확장이 본격적으로 이루어지고 있습니다. 아울러 가사 및 행정 분야 사건 역시 안정적으로 증가하고 있어, 초기 멤버로 합류하시는 변호사님께서는 특정 분야에 국한되지 않고, 본인의 성향과 역량에 따라 전문 분야를 확장하고 정착시킬 수 있을 것입니다. 리율은 이번 채용을 통해 채용되시는 변호사님들과 함께 사건을 단순히 처리하는 데 그치지 않고, 사건을 분석하고 업무 구조를 설계하며 법무법인의 방향성과 비전을 공유하는 동반자 관계를 구축하고자 합니다. 빠르게 성장하는 초기 법무법인의 핵심 멤버로서, 개인의 성장과 법인의 성장을 함께 실현하고자 하는 실무수습(15회 변호사시험) 변호사님들의 적극적인 지원을 기다립니다.",
    hiringCount: "채용분야 : 변호사\n변 호 사 : 2명",
    employmentType: "정규직",
    duties: "법률 자문 및 송무 지원",
    workStartDate: "2026-05-26",
    dailyWorkHours: "출근시간 : 9시 0분\n퇴근시간 : 18시 0분\n휴게시간 : 12시 30분 ~ 13시 30분\n기타 :",
    wage: "월 300만원 ~ 350만원 (세전)",
    overtimePay: "근로기준법에 따름",
    workPlace: "사무실",
    workDays: "월~금(주5일)",
    holidays: "토,일,법정공휴일",
    annualLeave: "기타 ( 근로기준법에 따름 )",
    fourInsurances: "기타 ( 근로기준법에 따름 )",
    maternityLeave: "기타 ( 근로기준법에 따름 )",
    menstrualLeave: "기타 ( 근로기준법에 따름 )",
    parentalLeave: "기타 ( 근로기준법에 따름 )",
    bonus: "기타 ( 사건수임, 업무 능력에 따른 상여금 )",
    mealSupport: "있음",
    otherBenefits: "1) 식비 및 야근식대, 재판출정 교통비 등 지원 2) 연차/반차 등의 휴가 3) 4대보험 및 퇴직연금 4) 월회비 지원 5) 사건수임에 대한 성과금 6) 업무 능력에 따른 상여금",
    career: "기타 ( 15회 변호사 시험에 합격한 변호사님 )",
    certifications: "",
    otherRequirements: "수습변호사 채용의 경우 3개월 시용계약 기간이 있습니다. / 시용기간 동안 업무성과가 평가기준에 미달하는 경우 채용이 불가할 수 있습니다.",
    preferences: "IT 분야와 화학 분야 전공자나 경력자 우대 /변리사 자격증 소지자 또는 2차 시험 응시자 우대",
    documents: "기타 ( ① 자유양식의 이력서(단, 출근가능일, 변호사시험 점수 기재는 필수) ② 자유양식의 자기소개서 ③ 학부·대학원·법학전문대학원 각 성적증명서 ④ 기타 지원자의 역량을 확인할 수 있는 서면, 과제물, 논문, 서류 또는 자료 )",
    process: "1차 서류전형 ( 일정 : 2026-05-26 )\n2차 면접 ( 일정 : 2026-05-26 )\n기타 : ① 1차는 서류전형으로 2차는 면접전형으로 진행 ② 서류전형 합격자에 한하여 개별 통지 후 면접 진행",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자유롭게 기술",
    applicationDeadline: "2026-05-26",
    notifyMethod: "개별 통지",
    applicationMethod: "이메일 : leeyul@lylaw.kr\n팩   스 : 02-6954-2633\n기   타 :",
    manager: "이   름 : 김동현\n연락처 : 02-573-2632",
    description: ""
  },
  {
    id: 8,
    source: "seoulbar",
    firm: "법무법인 지에스",
    title: "실무수습변호사 채용공고",
    postedAt: "2026-05-11",
    deadline: "2026-05-31",
    stage: "hidden",
    stageCheckedAt: "",
    address: "06606\n서울 서초구 서초중앙로24길 16 (서초동)\nKM타워 9층",
    representative: "김원균",
    homepage: "http://www.gslawyer.co.kr/html",
    contact: "02-535-1500",
    sizeAndEtc: "서울 주사무소, 수원 분사무소가 있고 서울에서 근무합니다.",
    hiringCount: "채용분야 : 민사, 형사, 행정 등 소송 업무\n변 호 사 : 1명",
    employmentType: "기타 ( 실무수습 후 정규직 전환 가능 )",
    duties: "민사, 형사, 행정 등 소송업무",
    workStartDate: "2026-06-01",
    dailyWorkHours: "출근시간 : 9시 0분\n퇴근시간 : 18시 0분\n휴게시간 : 12시 0분 ~ 13시 0분\n기타 :",
    wage: "월 250만원 ~ 300만원 (세전)",
    overtimePay: "근로기준법에 따름",
    workPlace: "사무실",
    workDays: "월~금(주5일)",
    holidays: "토,일,법정공휴일",
    annualLeave: "있음",
    fourInsurances: "있음",
    maternityLeave: "있음",
    menstrualLeave: "있음",
    parentalLeave: "있음",
    bonus: "없음",
    mealSupport: "있음",
    otherBenefits: "없음",
    career: "없음",
    certifications: "",
    otherRequirements: "",
    preferences: "",
    documents: "기타 ( 이력서 및 자기소개서 )",
    process: "1차 서류전형 ( 일정 : 2026-05-22 )\n2차 면접 ( 일정 : 2026-05-25 )\n기타 : 서류전형 후 면접(서류전형 합격자에 한하여 개별 통보합니다).",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자유롭게 기술",
    applicationDeadline: "2026-05-31",
    notifyMethod: "실무수습 대상자에게 개별 통지",
    applicationMethod: "이메일 : twobeen@naver.com\n팩   스 : 02-536-1400\n기   타 :",
    manager: "이   름 : 변호사 이재현\n연락처 : 010-4972-8112",
    description: ""
  },
  {
    id: 9,
    source: "seoulbar",
    firm: "법무법인 화온",
    title: "실무 수습 예비 변호사님을 모십니다.",
    postedAt: "2026-05-11",
    deadline: "2026-05-21",
    stage: "hidden",
    stageCheckedAt: "",
    address: "07242\n서울 영등포구 은행로 30 (여의도동, 중소기업중앙회)\n본관 7층",
    representative: "천재필, 오정환",
    homepage: "https://www.hwaon.com",
    contact: "02-2135-4211",
    sizeAndEtc: "변호사 8명, 직원 6명",
    hiringCount: "채용분야 : 송무 및 자문\n변 호 사 : 0명",
    employmentType: "정규직",
    duties: "송무 및 자문",
    workStartDate: "2026-05-04",
    dailyWorkHours: "출근시간 : 10시 0분\n퇴근시간 : 19시 0분\n휴게시간 : 12시 0분 ~ 13시 0분\n기타 :",
    wage: "월 300만원 ~ 350만원 (세전)",
    overtimePay: "근로기준법에 따름",
    workPlace: "사무실",
    workDays: "월~금(주5일)",
    holidays: "토,일,법정공휴일",
    annualLeave: "있음",
    fourInsurances: "있음",
    maternityLeave: "기타 ( 근로기준법에 따름 )",
    menstrualLeave: "기타 ( 근로기준법에 따름 )",
    parentalLeave: "기타 ( 근로기준법에 따름 )",
    bonus: "기타 ( 협의 )",
    mealSupport: "있음",
    otherBenefits: "협의",
    career: "없음",
    certifications: "",
    otherRequirements: "",
    preferences: "",
    documents: "기타 ( 이력서 및 자기소개서 )",
    process: "1차 서류전형 ( 일정 : 2026-05-22 )\n2차 면접 ( 일정 : 2026-05-22 )\n기타 :",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자유롭게 기술",
    applicationDeadline: "2026-05-21",
    notifyMethod: "합격자에 한해 개별통보",
    applicationMethod: "이메일 : recruit@hwaon.com\n팩   스 : 02-2135-4214\n기   타 :",
    manager: "이   름 : 이정민 대리\n연락처 : 02-2135-4263",
    description: "법무법인 화온은 2024년 10월 여의도에서 새로운 법률시장의 지형을 그리기 위해 출범한 신생 로펌입니다.\n\n김앤장과 서울고등법원 재판연구원 출신의 대표 변호사들이 뜻을 모아 설립한 화온은, 서로 배우고 협력하며 함께 성장하는 문화를 핵심 가치로 삼고 있습니다.\n\n현재 화온은 다양한 송무와 자문 사건을 안정적으로 수행하며, 빠르게 신뢰를 쌓아가고 있습니다.\n\n저희는 지금, 화온의 여정에 함께할 소속 변호사님을 찾고 있습니다.\n\n신생 법인의 가장 큰 매력은 기회와 변화의 가능성이 열려 있다는 것입니다.\n\n기존의 틀에 얽매이지 않고, 각자의 전문성과 개성을 살려 함께 성장할 수 있도록 저희는 전폭적으로 지원할 준비가 되어 있습니다.\n\n대형 로펌의 체계와 신생 로펌의 유연함을 동시에 경험할 수 있는 곳.\n\n주도적으로 성장하고 싶고, 새로운 가능성을 스스로 만들어가고 싶은 변호사님이라면, 언제든 화온의 문은 열려 있습니다."
  },
  {
    id: 10,
    source: "seoulbar",
    firm: "법무법인 우승",
    title: "[법무법인 우승] 수습변호사님을 모십니다(서초동)",
    postedAt: "2026-05-11",
    deadline: "2026-05-28",
    stage: "hidden",
    stageCheckedAt: "",
    address: "06601\n서울 서초구 서초중앙로24길 27 (서초동, G5센트럴프라자)\n209호",
    representative: "안병욱, 김용철, 박형남, 최호식, 이주형",
    homepage: "https://www.kpulaw.com/",
    contact: "02-6926-2936",
    sizeAndEtc: "변호사 30여명, 직원 10여명",
    hiringCount: "채용분야 :\n변 호 사 : 1명",
    employmentType: "정규직",
    duties: "송무, 자문",
    workStartDate: "2026-06-01",
    dailyWorkHours: "출근시간 : 9시 0분\n퇴근시간 : 6시 0분\n휴게시간 : 12시 0분 ~ 13시 10분\n기타 :",
    wage: "월 350만원 ~ 400만원 (세전)",
    overtimePay: "근로기준법에 따름",
    workPlace: "사무실",
    workDays: "월~금(주5일)",
    holidays: "토,일,법정공휴일",
    annualLeave: "있음",
    fourInsurances: "있음",
    maternityLeave: "기타 ( 협의 )",
    menstrualLeave: "기타 ( 협의 )",
    parentalLeave: "기타 ( 협의 )",
    bonus: "기타 ( 협의 )",
    mealSupport: "있음",
    otherBenefits: "출퇴근, 휴가사용등이 비교적 자유롭습니다. 식비제공",
    career: "없음",
    certifications: "",
    otherRequirements: "",
    preferences: "",
    documents: "기타 ( 이력서, 자기소개서, 성적증명서(로스쿨, 변호사시험)를 하나의 pdf파일로 합본하여 메일로 제출해 주시기 바랍니다. 파일 제목에 지원자의 성함을 기재해 주시기 바랍니다. )",
    process: "1차 서류전형 ( 일정 : 2026-05-28 )\n2차 면접 ( 일정 : 2026-05-29 )\n기타 : 서류접수 마감 전이라도 수시 면접을 진행할 수 있습니다.",
    resumeItems: "이름, 주소, 연락처, 학력, 자격증, 관련경력, 기타",
    coverLetterItems: "자유롭게 기술",
    applicationDeadline: "2026-05-28",
    notifyMethod: "서류 전형에 합격한 분에 한해 개별적으로 연락(전화 또는 문자)",
    applicationMethod: "이메일 : j26149@kpulaw.com\n팩   스 : 02-6925-3220\n기   타 : 이메일로 지원해 주시기 바랍니다.",
    manager: "이   름 : 안병욱 변호사\n연락처 : 02-6925-2936",
    description: "저희 법무법인 우승은 풍부한 실무 경험을 갖춘 변호사들이 함께하며, 다양한 법률 분야의 사건을 종합적으로 수행하고 있는 로펌입니다.\n\n2024년 법무법인 설립 후 안정적이면서도 꾸준한 성장을 이어오고 있습니다.\n\n실무수습 기간에 다양한 사건의 검토, 서면 작성, 자문에 대한 의견서 작성 등을 통하여 변호사 업무에 관한 제반 실무를 구체적으로 학습, 수행하고, 상담 동석, 재판 참관, 접견 등 현장 실무 수습을 체득할 기회를 제공하려고 합니다. 그리고 해당 사건을 담당하는 대표 변호사의 세심하고 깊이 있는 피드백, 멘토링을 통하여 신입 변호사님의 실무 수행 능력이 체계적으로 향상될 수 있도록 지원할 예정입니다.\n\n저희 법인은 실무수습 변호사님께 수습 기간 종료 후 평가를 거쳐 소속변호사로서의 채용 여부를\n다른 변호사 지원자보다 최우선적으로 고려할 예정입니다.\n\n더 큰 성장을 앞두고 있는 법무법인 우승에서 함께 성장하실 15회 변호사시험 합격자분들, 특히 도산사건에 관심이 있거나 전문분야로 삼고 싶으신 분들의 많은 지원 바랍니다."
  }
];
